#!/bin/sh
#
# Load all necessary st modules
# 
# chkconfig: S 9 0
#

echo "init frontpanel"
modprobe aotom
modprobe simu_button
mknod -m 644 /dev/vfd c 147 0
mknod -m 644 /dev/hdmi_cec c 149 0
modprobe e2_proc

   echo "init stmfb"
   modprobe stmcore-display-sti7111
   modprobe stmfb display0=1280x720-32@50:8m:46m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;

   echo "LOADING MODULES"   
   echo "LOAD" > /dev/vfd

   if [ ! -e /boot/audio.elf ]; then
      echo "FW MISSING!!!"
   fi
      /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
      /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   modprobe embxshell
   modprobe embxmailbox mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   modprobe embxshm mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   modprobe mme_host transport0=shm

   echo "init AVS"
   modprobe avs type=avs_pio
   player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
   echo "init player $player"

   modprobe mmelog
   modprobe ksound
   modprobe p2div64
   modprobe stm_v4l2
   if [ $player -gt 131 ]; then
      modprobe stmvout
      modprobe stmvbi
   fi
   modprobe pseudocard

   modprobe stv090x
#  modprobe lnb
   if [ $player -gt 131 ]; then
      # Full feature pti
      modprobe pti waitMS=20 videoMem=4096
      if [ $?=='2' ]; then
         # Simple pti
         modprobe pti
      fi
      modprobe stm_monitor
      modprobe stmsysfs
      modprobe stmdvb
   else
      modprobe pti
      modprobe stmdvb
      modprobe stm_monitor
   fi
   modprobe player2 discardlateframe=0
   modprobe sth264pp
   modprobe stmalloc
   modprobe platform
   modprobe silencegen
   modprobe smartcard
   modprobe bpamem
   modprobe cec
#   mknod /dev/bpamem c 153 0 

   major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
#   rm -f /dev/sparkid
#   mknod /dev/sparkid c $major 0 

	stfbcontrol a 255
	echo " e2 "
