#!/bin/sh
#
# lirc daemon
# chkconfig: S 36 80
#
PID=/var/run/lirc/lircd.pid

test -e /dev/lirc || ln -s lirc0 /dev/lirc

boxver()
{
	if test -z "$STB_ID"; then
		eval $(sed 's/^.* \(STB_ID[^[:space:]]*\).*$/\1/' /proc/cmdline)
	fi
	BOX_ID=${STB_ID:0:8}	# 09:00:07
	BOX_ID=${BOX_ID//:/_}	# 09_00_07
	export BOX_ID
}

case $1 in
	start)
		echo -n "Starting lircd "
		boxver	# determine boxtype
		# if a /etc/lircd.conf.$BOX_ID exists, use it...
		test -z "$LIRCD_OPTS" && test -e /etc/lircd.conf.$BOX_ID && LIRCD_OPTS=/etc/lircd.conf.$BOX_ID
		/usr/bin/lircd $LIRCD_OPTS
		start-stop-daemon -S -b -x /bin/evremote2
		echo "."
		echo "LIRCD_OPTS = $LIRCD_OPTS"
		;;
	stop)
		echo -n "Stopping lircd "
		start-stop-daemon -K -x /bin/evremote2
		kill -TERM `cat $PID`
		echo "."
		;;
	restart)
		echo -n "Restarting lircd... "
		$0 stop
		$0 start
		;;
	*)
		echo   "usage:	$0 <start|stop|restart>"
		exit 1
		;;
esac
