#!/bin/sh
#
# lirc daemon
# chkconfig: S 36 80
#
PID=/var/run/lirc/lircd.pid

[ -e /dev/lirc ] || ln -s lirc0 /dev/lirc
[ -d /var/run/lirc ] || mkdir -p /var/run/lirc
boxver()
{
	STB_ID=`sed 's/.*STB_ID=//;s/ .*//;/[:]/!d;s/:/_/g' /proc/cmdline`
	[ -z "$STB_ID" ] && STB_ID=`sed 's/.*ethaddr://;s/ .*//;/[:]/!d;s/^24/09/;s/:/_/g' /proc/cmdline`
	BOX_ID=${STB_ID:0:8}
}

case $1 in
	start)
		echo -n "Starting lircd "
		boxver	# determine boxtype
		# if a /etc/lircd.conf.$BOX_ID exists, use it...
		[ -z "$LIRCD_OPTS" ] && [ -e /etc/lircd.conf.$BOX_ID ] && LIRCD_OPTS=/etc/lircd.conf.$BOX_ID
		/usr/bin/lircd $LIRCD_OPTS
		start-stop-daemon -S -b -x /bin/evremote2
		echo "."
		echo "LIRCD_OPTS = $LIRCD_OPTS"
		;;
	stop)
		echo -n "Stopping lircd "
		start-stop-daemon -K -x /bin/evremote2
		kill -TERM `cat $PID`
		echo "."
		;;
	restart)
		echo -n "Restarting lircd... "
		$0 stop
		$0 start
		;;
	*)
		echo   "usage:	$0 <start|stop|restart>"
		exit 1
		;;
esac
