#!/bin/sh

MODDIR=/lib/modules
echo "init frontpanel"
insmod $MODDIR/proton.ko
insmod $MODDIR/simu_button.ko
   echo "ОЖИДАЙТЕ" > /dev/vfd
   echo "WAIT 1 min"
if [ -e /var/etc/.firstboot ]; then
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start
/usr/sbin/automount --timeout=5 /autofs file /etc/auto.usb
insmod $MODDIR/e2_proc.ko

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-stx7109c3.ko
   insmod $MODDIR/stmfb.ko display0=1920x1080-32@50:12m:pal:yuv:yuv

   echo "LOADING MODULES"
   echo "ЗАГРУЗКА" >/dev/vfd

   echo "load a firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko type=stv6418
   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0;
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/kreplay.ko
   insmod $MODDIR/silencegen.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/pseudocard.ko
   
   echo "init frontends"
   insmod $MODDIR/fe-core.ko demod=stv090x tuner=stv6110x

   echo "init drivers"
   insmod $MODDIR/cimax.ko
   insmod $MODDIR/pti.ko waitMS=20 videoMem=10240
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/player2.ko discardlateframe=0
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko

   showiframe -p /boot/bootlogo.mvi &
   
   echo "init lircd"
   /usr/bin/lircd
   
   /bin/evremote2 hl101 &
   
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   /var/bin/swap start
   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/login
   /etc/init.d/vsftpd start
   /usr/sbin/inetd
 
   NFS=`grep -c nfs /proc/cmdline`
   if [ "$NFS" -eq "1" ]; then 
      echo "Booting from nfs, don't set network" 
   else 
      if [ -e /etc/network/interfaces ]; then 
	 ip addr flush eth0 
	 /etc/init.d/networking stop 
	 DHCP=`grep -c dhcp /etc/network/interfaces`
	 if [ "$DHCP" -eq "1" ]; then 
	    echo "Starting dhcp"
            /etc/init.d/udhcpc start 
	 fi 
	 /etc/init.d/networking start 
      fi 
   fi
   
   mount /dev/sdb1 /hdd/movie
   
   echo "РУНИГМА" > /dev/vfd
   echo "LOADING RUNIGMA"

   until false
   do
      echo "starting enigma2->"
	  /var/bin/gmt.sh &
	  /var/bin/emustarter.sh &
	  /var/bin/opkg.sh &
	  /hdd/epg.conf &
      /usr/local/bin/enigma2.sh
      rtv=$?
      echo "e2 ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "E2 ERROR"
           echo "0" > /proc/progress;;
		1) echo "1"
		   echo "SHUTDOWN"
		   /bin/shutdown.sh;;
		2) echo "2"
		   echo "REBOOT"
		   /etc/init.d/reboot;;
		3) echo "3"
		   echo "E2 RESTART"
		   echo "0" > /proc/progress;;
		*) echo "*"
		   echo "ERROR"
           echo "0" > /proc/progress;;
      esac
   done 
fi

#never reached
echo "REBOOT HL101" > /dev/vfd
echo "REBOOT HL101"
reboot 
