#!/bin/sh

MODDIR=/lib/modules
echo "init frontpanel"
insmod $MODDIR/proton.ko gmt=+400
insmod $MODDIR/simu_button.ko
   echo "ОЖИДАЙТЕ" > /dev/vfd
   echo "WAIT 1 min"
if [ -e /var/etc/.firstboot ]; then
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start

insmod $MODDIR/e2_proc.ko

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-stx7109c3.ko
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv

   echo "LOADING MODULES"
   echo "ЗАГРУЗКА" >/dev/vfd

   echo "load a firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko type=stv6418
   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER1;
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/kreplay.ko
   insmod $MODDIR/silencegen.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/pseudocard.ko
   
   echo "init frontends"
   insmod $MODDIR/fe-core.ko demod=stv090x tuner=stv6110x

   echo "init drivers"
   insmod $MODDIR/cimax.ko
   insmod $MODDIR/pti.ko waitMS=30 videoMem=4096
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/player2.ko discardlateframe=0
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/smartcard.ko debug=1

   showiframe -p /boot/RUnigmaHD-VIP-start.mvi &
   
   echo "init lircd"
   /usr/bin/lircd

   mknod /dev/rc c 147 1 
   mknod /dev/sci0 c 169 0
   mknod /dev/sci1 c 169 1 
   
   /bin/evremote2 hl101 &

   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/login
   /etc/init.d/vsftpd start
   /usr/sbin/inetd
 
   if [ -e /etc/network/interfaces ]; then 
	 ip addr flush eth0 
	 /etc/init.d/networking stop 
	 DHCP=`grep -c dhcp /etc/network/interfaces`
   if [ "$DHCP" -eq "1" ]; then 
	    echo "Starting dhcp"
            /etc/init.d/udhcpc start 
   fi 
	 /etc/init.d/networking start 
   fi 

   touch /dev/.udev

   echo "РУНИГМА" > /dev/vfd
   echo "LOADING RUNIGMA"

   until false
   do
      echo "starting enigma2->"
	  /usr/sbin/ntpdate ru.pool.ntp.org &
	  /var/bin/emustarter.sh &
	  /var/bin/opkg.sh &
	  /hdd/epg.conf &
      /usr/local/bin/enigma2
      rtv=$?
      echo "e2 ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "E2 ERROR"
           echo "0" > /proc/progress
		   showiframe -p /boot/RUnigmaHD-VIP-restartGUI.mvi &;;
		1) echo "1"
		   echo "SHUTDOWN"
		   /bin/shutdown.sh;;
		2) echo "2"
		   echo "REBOOT"
		   /etc/init.d/reboot
           showiframe -p /boot/RUnigmaHD-VIP-restart.mvi &
           /etc/init.d/reboot;;
		3) echo "3"
		   echo "E2 RESTART"
		   echo "0" > /proc/progress
		   showiframe -p /boot/RUnigmaHD-VIP-restartGUI.mvi &;;
		*) echo "*"
		   echo "ERROR"
           echo "0" > /proc/progress
		   showiframe -p /boot/RUnigmaHD-VIP-restartGUI.mvi &;;
      esac
   done 
fi

#never reached
echo "REBOOT HL101" > /dev/vfd
echo "REBOOT HL101"
reboot 
