#!/bin/sh

MODDIR=/lib/modules
echo "init frontpanel"
modprobe aotom
modprobe simu_button

if [ -e /var/etc/.firstboot ]; then
   echo "WAIT 1 min" >/dev/vfd
   echo "WAIT 1 min"
   rm /var/etc/.firstboot
   /etc/init.d/makedev start
fi

/etc/init.d/mountvirtfs start
/etc/init.d/portmap start

modprobe e2_proc

/etc/init.d/autofs start

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin

   echo "init stmfb"
   modprobe stmcore-display-sti7105
   modprobe stmfb display0=1280x720-32@50:15m:pal:yuv:yuv

   echo "LOADING MODULES"   
   echo "LOAD" > /dev/vfd

   if [ ! -e /boot/audio.elf ]; then
      echo "FW MISSING!!!"
   fi

   echo "load a firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   modprobe embxshell
   modprobe embxmailbox mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   modprobe embxshm mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   modprobe mme_host transport0=shm

   echo "init AVS"
   modprobe avs type=avs_pio
   player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
   echo "init player $player"

   modprobe mmelog
   modprobe ksound
   modprobe p2div64
   modprobe stm_v4l2
   if [ $player -gt 131 ]; then
      modprobe stmvout
      modprobe stmvbi
   fi
   modprobe pseudocard

   modprobe spark7162
   if [ $player -gt 131 ]; then
      # Full feature pti
      modprobe pti waitMS=20 videoMem=4096
      if [ $?=='2' ]; then
         # Simple pti
         modprobe pti
      fi
      modprobe stm_monitor
      modprobe stmsysfs
      modprobe stmdvb
   else
      modprobe pti
      modprobe stmdvb
      modprobe stm_monitor
   fi
   modprobe player2 discardlateframe=0
   modprobe sth264pp
   modprobe stmalloc
   modprobe platform
   modprobe silencegen
   modprobe smartcard
   modprobe bpamem
   mknod /dev/bpamem c 153 0 

   showiframe -p /boot/bootlogo.mvi &
   stfbcontrol a 0

   echo "init lircd"
   /usr/bin/lircd

   mknod /dev/rc c 147 1 
   mknod /dev/sci0 c 169 0
   mknod /dev/sci1 c 169 1 
   major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
   rm -f /dev/sparkid
   mknod /dev/sparkid c $major 0 

   /bin/evremote2 10 100 &

   stfbcontrol a 255

   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

	mknod /dev/dvb/adapter0/frontend1 c 212 19
	mknod /dev/dvb/adapter0/frontend2 c 212 35
	mknod /dev/dvb/adapter0/frontend3 c 212 51
	
NFS=`grep -c nfs /proc/cmdline`
   if [ "$NFS" -eq "1" ]; then 
      echo "Booting from nfs, don't set network" 
   else 
      if [ -e /etc/network/interfaces ]; then 
	  ip addr flush eth0
	 /etc/init.d/networking stop
	 DHCP1=`grep -c 'auto wlan0' /etc/network/interfaces`
	 DHCP2=`grep -c 'auto eth0' /etc/network/interfaces`
	 if [ "$DHCP1" -eq "1" ]; then 
	    echo "Starting wlan0 dhcp"
         /etc/init.d/networking start
	  /etc/init.d/avahi-daemon start
	 ifconfig eth0 down
	 elif [ "$DHCP2" -eq "1" ]; then 
	    echo "Starting eth0 dhcp"
            /etc/init.d/networking start
	 fi 
      fi 
   fi

   echo "run" > /dev/vfd
   echo "LOADING E2"
   # cron daemon
   (sleep 60; /usr/sbin/crond) & 
   until false
   do
      echo "starting e2->"
      crontab /var/spool/cron/crontabs/root
      /usr/lib/enigma2/python/Plugins/Extensions/AR-P/automount.sh

      STARTUP=`grep -c 'titan' /etc/init.d/start`
      if [ "$STARTUP" -eq "1" ]; then
      /usr/local/bin/titan /etc/titan/titan.cfg
      else
      if [ ls /hdd/enigma2_crash_??????????.log >/dev/null 2>&1 ]; then
        mv /hdd/enigma2_crash_??????????.log /hdd/enigma2_crash_??????????_.log
        cd /etc/enigma2
        sed -i "/$config.skin./d" "settings"
      fi
      /usr/local/bin/enigma2
      fi
      rtv=$?
      echo "e2 ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "E2 ERROR"
      		   init 6;;
		1) echo "1"
		   echo "SHUTDOWN"
                   init 0;;
		2) echo "2"
		   echo "REBOOT"
		   init 6;;
		3) echo "3"
		   echo "E2 RESTART"
		   echo "0" > /proc/progress
		   showiframe -p /boot/bootlogo.mvi &;;
		*) echo "*"
		   echo "ERROR"
		   killall -9 enigma2;;
      esac
   done 
fi

#never reached
echo "REBOOT SPARK-7162" > /dev/vfd
echo "REBOOT SPARK-7162"
reboot -f
