#! /bin/sh
#
# reboot	Execute the reboot command.
#
# Version:      @(#)reboot  2.75  22-Jun-1998  miquels@cistron.nl
#
# chkconfig: S 0 100
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin

echo -n "Rebooting... "
reboot -f
