#!/bin/sh
#
#
#
#
# syslogd
#chkconfig: S 03 0
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON="/sbin/syslogd"
OPTIONS="-l7 -s1000 -b0"
DESC="syslogd/klogd"

# Defaults
CONFIGFILE="/etc/syslogd.conf"

set -e

case "$1" in
  start)
	echo "Starting $DESC... "
	start-stop-daemon --start --exec /sbin/syslogd -- $OPTIONS
	start-stop-daemon --start --exec /sbin/klogd
		#--exec $DAEMON -- -f $CONFIGFILE
	echo "done."
	;;
  stop)
	echo "Stopping $DESC... "
	start-stop-daemon --stop --exec /sbin/syslogd
	start-stop-daemon --stop --exec /sbin/klogd
	echo "done."
	;;
  restart)
	echo "Restarting $DESC... "
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
