#!/bin/sh
#
#
#
#
# syslogd
#chkconfig: S 03 0
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON="/sbin/syslogd"
OPTIONS="-l7 -s1000 -b0"
DESC="System logger"
NAME=syslogd

test -x $DAEMON || exit 0

# Defaults
CONFIGFILE="/etc/syslogd.conf"
USERID=root
GROUPID=root
ENABLE="true"

if [ "$ENABLE" != "true" ]; then
	echo "$NAME daemon disabled "
	exit 0
fi

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet --chuid $USERID:$GROUPID \
		--exec $DAEMON  -- $OPTIONS
		#--exec $DAEMON -- -f $CONFIGFILE
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --oknodo --quiet --exec $DAEMON
	echo "$NAME."
	;;

  restart)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --oknodo --quiet --exec $DAEMON
	echo "done."
	sleep 1
	start-stop-daemon --start --quiet --chuid $USERID:$GROUPID \
		--exec $DAEMON -b --
	echo "$NAME."
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
