SECTION ?= base
PRIORITY ?= optional
LICENSE ?= unknown
HOMEPAGE ?= unknown

PACKAGE_PARAMS_LIST := PKGV PKGR DESCRIPTION SECTION PRIORITY MAINTAINER LICENSE PACKAGE_ARCH HOMEPAGE RDEPENDS RREPLACES RCONFLICTS SRC_URI FILES

EXPORT_ALLENV = $(shell echo '$(.VARIABLES)' | awk -v RS=' ' '/^[a-zA-Z0-9_]+$$/')
EXPORT_ENV = $(filter PACKAGES, $(EXPORT_ALLENV))
EXPORT_ENV += $(filter $(PACKAGE_PARAMS_LIST), $(EXPORT_ALLENV))
EXPORT_ENV += $(filter $(addsuffix _%, $(PACKAGE_PARAMS_LIST) FILES NAME), $(EXPORT_ALLENV))
export $(EXPORT_ENV)